name: UpdateHosts

on:
  workflow_dispatch:
    inputs:
      ssh:
        description: 'SSH connection to Actions'
        required: false
        default: 'false'
  push:
    branches:    
      - main
  schedule:
    - cron: '0 */6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9]

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f ./workingDir/requirements ]; then pip install -r ./workingDir/requirements; fi

    - name: Update hosts
      run: cd workingDir/ && bash runAllShellScript.sh

    - name: Commit changes
      id: commit
      run: |
        git config --global user.email github-actions[bot]@users.noreply.github.com
        git config --global user.name action_bot
        git add .
        git commit -m "update hosts" || echo "Nothing to commit"
          continue-on-error: true

    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ github.ref }}

    - name: Delete workflow runs
      uses: Mattraks/delete-workflow-runs@v2
      with:
        retain_days: 0.1
        keep_minimum_runs: 1
